gcAuthenticatedRegistry: "airgap.vmvo.registry.vf/library/authenticated-image-pulling"
promoterE2eRegistry: "airgap.vmvo.registry.vf/library/e2e-test-images"
buildImageRegistry: "airgap.vmvo.registry.vf/library/build-image"
invalidRegistry: "airgap.vmvo.registry.vf/library/invalid"
gcEtcdRegistry: "airgap.vmvo.registry.vf/library"
gcRegistry: "airgap.vmvo.registry.vf/library"
sigStorageRegistry: "airgap.vmvo.registry.vf/library/sig-storage"
privateRegistry: "airgap.vmvo.registry.vf/library/k8s-authenticated-test"
microsoftRegistry: "airgap.vmvo.registry.vf/library"
dockerLibraryRegistry: "airgap.vmvo.registry.vf/library"
cloudProviderGcpRegistry: "airgap.vmvo.registry.vf/library/cloud-provider-gcp"